name: "Check for changes in paths"

on:
  workflow_call:
    outputs:
      actions:
        value: ${{ jobs.changed.outputs.actions }}
      docs:
        value: ${{ jobs.changed.outputs.docs }}

permissions:
  contents: read
  pull-requests: read

jobs:
  changed:
    runs-on: ubuntu-24.04
    outputs:
      actions: ${{ steps.changes.outputs.actions }}
      docs: ${{ steps.changes.outputs.docs }}
    steps:
      # https://github.com/marketplace/actions/checkout
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      # https://github.com/marketplace/actions/paths-changes-filter
      - name: Paths Changes Filter
        uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36 # v3.0.2
        id: changes
        with:
          filters: |
            actions:
              - '.github/workflows/*.yml'
            docs:
              - 'public/**/*'
              - 'src/**/*'
              - '.tool-versions'
              - 'astro.config.mjs'
              - 'package.json'
              - 'tsconfig.json'
