name: "Check for changes in paths"

on:
  workflow_call:
    outputs:
      actions:
        value: ${{ jobs.changed.outputs.actions }}
      docs:
        value: ${{ jobs.changed.outputs.docs }}

permissions:
  contents: read
  pull-requests: read

jobs:
  changed:
    runs-on: ubuntu-24.04
    outputs:
      actions: ${{ steps.changes.outputs.actions }}
      docs: ${{ steps.changes.outputs.docs }}
    steps:
      # https://github.com/marketplace/actions/checkout
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      # https://github.com/marketplace/actions/paths-changes-filter
      - name: Paths Changes Filter
        uses: dorny/paths-filter@fbd0ab8f3e69293af611ebaee6363fc25e6d187d # v4.0.1
        id: changes
        with:
          filters: |
            actions:
              - '.github/workflows/*.yml'
            docs:
              - 'public/**/*'
              - 'src/**/*'
              - '.tool-versions'
              - 'astro.config.mjs'
              - 'package.json'
              - 'tsconfig.json'
